from datetime import time as t

Grave = {'Regular': {'start1': t(23, 20),
                     'end1':   t(1, 0),
                     'start2': t(1, 20),
                     'end2':   t(3, 0),
                     'start3': t(3, 35),
                     'end3':   t(5, 0),
                     'start4': t(5, 20),
                     'end4':   t(7, 0),
                     'start5': None,
                     'end5':   None,
                     'start6': None,
                     'end6':   None,
                     'start7': None,
                     'end7':   None,
                     'start8': None,
                     'end8':   None,
                     },
         'Department Lunch': {'start1': t(23, 20),
                              'end1':   t(1, 0),
                              'start2': t(1, 20),
                              'end2':   t(3, 0),
                              'start3': t(4, 35),
                              'end3':   t(7, 0),
                              'start4': None,
                              'end4':   None,
                              'start5': None,
                              'end5':   None,
                              'start6': None,
                              'end6':   None,
                              'start7': None,
                              'end7':   None,
                              'start8': None,
                              'end8':   None,
                              }
         }
Day = {'Regular': {'start1': t(7, 20),
                   'end1':   t(9, 0),
                   'start2': t(9, 20),
                   'end2':   t(11, 15),
                   'start3': t(11, 50),
                   'end3':   t(13, 30),
                   'start4': t(13, 50),
                   'end4':   t(15, 0),
                   'start5': None,
                   'end5':   None,
                   'start6': None,
                   'end6':   None,
                   'start7': None,
                   'end7':   None,
                   'start8': None,
                   'end8':   None,
                   },
       'Department Lunch': {'start1': t(7, 20),
                            'end1':   t(9, 0),
                            'start2': t(9, 20),
                            'end2':   t(11, 15),
                            'start3': t(12, 35),
                            'end3':   t(15, 0),
                            'start4': None,
                            'end4':   None,
                            'start5': None,
                            'end5':   None,
                            'start6': None,
                            'end6':   None,
                            'start7': None,
                            'end7':   None,
                            'start8': None,
                            'end8':   None,
                            },
       'Pit Stop': {'start1': t(8, 15),
                    'end1':   t(9, 0),
                    'start2': t(9, 20),
                    'end2':   t(11, 15),
                    'start3': t(11, 50),
                    'end3':   t(13, 30),
                    'start4': t(13, 50),
                    'end4':   t(15, 0),
                    'start5': None,
                    'end5':   None,
                    'start6': None,
                    'end6':   None,
                    'start7': None,
                    'end7':   None,
                    'start8': None,
                    'end8':   None,
                    },
       }
Swing = {'Regular': {'start1': t(15, 20),
                     'end1':   t(17, 0),
                     'start2': t(17, 20),
                     'end2':   t(19, 0),
                     'start3': t(19, 35),
                     'end3':   t(21, 0),
                     'start4': t(21, 20),
                     'end4':   t(23, 0),
                     'start5': None,
                     'end5':   None,
                     'start6': None,
                     'end6':   None,
                     'start7': None,
                     'end7':   None,
                     'start8': None,
                     'end8':   None,
                     },
         'Department Lunch': {'start1': t(15, 20),
                              'end1':   t(17, 0),
                              'start2': t(17, 20),
                              'end2':   t(19, 0),
                              'start3': t(20, 35),
                              'end3':   t(23, 0),
                              'start4': None,
                              'end4':   None,
                              'start5': None,
                              'end5':   None,
                              'start6': None,
                              'end6':   None,
                              'start7': None,
                              'end7':   None,
                              'start8': None,
                              'end8':   None,
                              }
         }
